status parameter to pitft script

diff --git a/bin/pitft b/bin/pitft
--- a/bin/pitft
+++ b/bin/pitft
@@ -1,26 +1,39 @@
 #!/bin/bash
 
 if [ "$1" == "--help" ]; then
-	echo "Usage: pitft <0 or 1>"
-	echo "turn off (0) or on (1) the Raspberry PI TFT display"
-	echo
-	exit -1
+	echo "Usage: pitft <0 or 1>";
+	echo "turn off (0) or on (1) the Raspberry PI TFT display";
+	echo;
+	echo "pitft status";
+	echo "returns 1 or 0 accoding to the display status";
+	echo;
+	exit 1;
 fi
 
 if [ -z $1 ]; then
-	echo Please set 0 or 1.
+	echo "Please set 0, 1 or status."
 	echo
-	exit -1
+	exit 1;
+fi
+
+if [ "$1" == "status" ]; then
+	if [ ! -f /sys/class/gpio/gpio508/value ]; then
+		echo "gpio508 file not found"
+		echo
+		exit 1;
+	fi
+	cat /sys/class/gpio/gpio508/value;
+	exit 0;
 fi
 
 if [ "$1" != "0" ] && [ "$1" != "1" ]; then
-	echo Invalid parameter. Please set 0 or 1.
+	echo "Invalid parameter. Please set 0, 1 or status."
 	echo
-	exit -1
+	exit 1;
 fi
 
 
-if [ ! -L /sys/class/gpio/export ]; then
+if [ ! -L /sys/class/gpio/gpio508 ]; then
 	echo 508 > /sys/class/gpio/export
 fi
 
