check for w3m

diff --git a/bin/securityheaders b/bin/securityheaders
--- a/bin/securityheaders
+++ b/bin/securityheaders
@@ -14,6 +14,7 @@ if [ -z "$1" ] || [ "$1" == "--help" ]; then
     exit 1
 fi
 
+command -v w3m >/dev/null 2>&1 || { echo >&2 "I require w3m, but it's not installed. Aborting."; exit 1; }
 
 SITE="$1"
 TEMP1=$(mktemp)
