fixed installers

diff --git a/soft_installers/tor_install b/soft_installers/tor_install
--- a/soft_installers/tor_install
+++ b/soft_installers/tor_install
@@ -11,9 +11,9 @@ installer_bootstrap
 
 TORBASEURL="https://www.torproject.org/dist/"
 if [ "$(which lynx)" != "" ]; then
-	TORFILENAME=$(lynx -dump https://www.torproject.org/dist/ | grep "tor-" | grep -v TXT | grep -v alpha | grep -v rc.tar | awk -F] '{ print $ 3;  }' | awk '{ print $1; }' | head -n 1)
+	TORFILENAME=$(lynx -nolist -dump $TORBASEURL | grep .tar.gz | grep -v .asc | grep -v alpha.tar | awk '{ print $4_$5" "$3; }' | sort -r | awk '{ print $2; }' | head -1)
 elif [ "$(which w3m)" != "" ]; then
-	TORFILENAME=$(w3m -dump https://www.torproject.org/dist/ | grep "tor-" | grep -v TXT | grep -v alpha | grep -v rc.tar | awk -F] '{ print $ 2;  }' | awk '{ print $1; }' | head -n 1)
+	TORFILENAME=$(w3m -dump $TORBASEURL | grep .tar.gz | grep -v .asc | grep -v alpha.tar | awk '{ print $4_$5" "$3; }' | sort -r | awk '{ print $2; }' | head -1)
 else
 	echo "Yout must have 'w3m' or 'lynx' installed to proceed."
 	abort_install
@@ -25,19 +25,22 @@ echo "DOWNLOADING TOR"
 echo
 
 cd $APPFOLDER
-download $TORBASEURL$TORFILENAME
+
+mkdir source-$TORNAME
+cd source-$TORNAME
+
+wget $TORBASEURL$TORFILENAME
 
 if [ ! -f "$TORFILENAME" ]; then
 	echo "Error downloading TOR."
 	abort_install
 fi
 
-
 echo ""
 echo "EXTRACTING FILES"
 echo ""
 
-tar xvzf $TORFILENAME
+tar xvzf $TORFILENAME || { echo "Error extracting file. Aborted"; abort_install;}
 
 echo ""
 echo "ORGANIZING $APPFOLDER"
